changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
url=jdbc:mysql://localhost:3306/library_booking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
password=root
driver=com.mysql.cj.jdbc.Driver
classpath=target/classes
